allow.room.status.change=${ALLOW_ROOM_STATUS_CHANGE:true}
guest.history.limit=${GUEST_HISTORY_LIMIT:2}

db.url=${DB_URL:jdbc:postgresql://localhost:5432/SENLA-11}
db.user=${DB_USER:admin}
db.password=${DB_PASSWORD:admin}

hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
hibernate.show_sql=${HIBERNATE_SHOW_SQL:false}
hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
hibernate.hbm2ddl.auto=${HIBERNATE_HBM2DDL_AUTO:validate}
hibernate.use_sql_comments=${HIBERNATE_USE_SQL_COMMENTS:true}
hibernate.connection.pool_size=${HIBERNATE_CONNECTION_POOL_SIZE:10}

jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}