allow.room.status.change=${ALLOW_ROOM_STATUS_CHANGE:true}
guest.history.limit=${GUEST_HISTORY_LIMIT:2}

db.url=${DB_URL:jdbc:postgresql://localhost:5432/SENLA-11}
db.user=${DB_USER:admin}
db.password=${DB_PASSWORD:admin}


jwt.secret=mySecretKeyForJWT1234567890abcdefghijklmnopqrstuvwxyzABCDEFGH
jwt.expirationMs=86400000

logging.level.org.springframework.security=DEBUG
